# Generated by Django 4.1.7 on 2023-03-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=200)),
            ],
        ),
    ]
