# Generated by Django 4.1.7 on 2023-03-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
